### ISSUE TITLE
Consider merging with school-comms.git

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/team-emails#2]
https://www.studentrobotics.org/cgit/school-comms.git exists for the same purpose as this repo. We should combine them.

**Comment by RealOrangeOne** [comment]
I agree. I'm hoping I can find a way to merge the repos, somehow. As re-committing all those files would be very destructive to the history!

**Comment by PeterJCLaw** [comment]
You're in for a treat. Git repos can be merged -- this is a completely normal out-of-the-box supported feature.
I'm not sure it was an _intentional_ feature, but it is one which has been used on a number of large scale projects and is something which "just works" because of the nature of git.

I can't find a link, but at some point in its history there's a merge of the `gitk` sources into the `git` repo, and a post (that I was hoping to link to) where linus talks about doing this and how's completely fine.

The mechanics of doing this are:
1. clone first repo
2. fetch _other_ repo into the same working clone
    - this will warn you about not having any "common ancestors", but that's fine here as that's somewhat the point
3. merge the commit from the other repo
    - you might need to use something like `FETCH_HEAD` to reference it
    - I'm told that modern git will again warn about the lack of common ancestor and might need an extra flag passing to let it know that this is expected; I don't recall having to do this, but I've also not done one of these in a while
