### ISSUE TITLE
RFC: Templates?

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/team-emails#39]
Many of the emails we write and send to teams are almost identical year-on-year. Besides the specific details, we always send:

- Team signup announcement
- Competition place confirmation
- Kickstart announcement
- Tech day announcement
- Competition date announcement
- MCFs

Some of these may be better as snippets rather than fully-fledged emails, but that's an implementation detail.

It would be good to create some basic templates for all these, where simple information needs to be plugged in. This has a couple benefits:

- Barrier to entry for writing emails is lower
- Chances of missing information year-on-year is reduced
- Language identity in emails is more cohesive

I suspect the best place for these would be committed into this repo, or perhaps the runbook?

**Comment by PeterJCLaw** [comment]
Templates sound like a good idea. I think we should make a general decision about whether templates go in the runbook or in more specific places (that probably warrants an issue on the runbook repo); currently it's a bit of a mix & match scenario. I think I'm slightly in favour of the templates being in the more specific places, though there are questions about what that means for things which don't currently have their own repos but do have historic records in the runbook.

I'd be open to having templates in this repo for now and potentially moving them later. Either way, we should review and either update or remove the previous examples of these emails which do exist in the Runbook already.

**Comment by PeterJCLaw** [comment]
It's been a few years, we've not needed these. Having the historical emails to work from has usually be enough.

Suggest we close this @RealOrangeOne?

**Comment by RealOrangeOne** [comment]
It's a nice idea, and still not ruled out, but I agree our current strategy of reusing previous emails has worked well for us so far. Since I opened the issue we have many more examples too which makes finding examples much simpler.
